name: build
on:
  push:
    branches: 
      - master
  pull_request:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: arduino/arduino-lint-action@v1
        with:
          library-manager: update
          compliance: strict
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install catch valgrind
      - name: Test with catch
        run: |
          cd tests
          make check
